apiVersion: apps/v1
kind: Deployment
metadata:
  name: spear-deployment  
spec:
  replicas: 1
  selector:
    matchLabels: 
      component: spear-web
  template:
    metadata:
      labels:
        component: spear-web
    spec:
      containers:
        - name: spear-web
          image: bobjwalker99/spear:6.0.9
          imagePullPolicy: "Always"
          ports:
           - containerPort: 8080
             name: http-port
          env:
           - name: SPEAR_SUMOLOGIC_URL
             valueFrom:
               secretKeyRef:
                 name: spear-credentials
                 key: sumologicUrl
           - name: SPEAR_INSTANCE_URL
             valueFrom:
               secretKeyRef:
                 name: spear-credentials
                 key: instanceUrl
           - name: SPEAR_INSTANCE_API_KEY
             valueFrom:
               secretKeyRef:
                 name: spear-credentials
                 key: instanceApiKey
           - name: SPEAR_ENVIRONMENT
             valueFrom:
               secretKeyRef:
                 name: spear-credentials
                 key: environment
           - name: SPEAR_OPEN_FEATURE_CLIENT_ID
             valueFrom:
               secretKeyRef:
                 name: spear-credentials
                 key: openFeatureClientId
---
apiVersion: v1
kind: Service
metadata:
  name: spear-app-cluster-ip-service  
spec:
  type: ClusterIP
  selector:
    component: spear-web
  ports:
    - port: 6800
      targetPort: 8080  
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:    
  name: spear-gateway  
spec:
  gatewayClassName: istio
  listeners:
  - hostname: spearlocal.local
    name: spear-gateway-http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: spear-local-httproute  
spec:
  hostnames:
  - spearlocal.local
  parentRefs:
  - name: spear-gateway    
  rules:
  - backendRefs:
    - name: spear-app-cluster-ip-service
      port: 6800
    matches:
    - path:
        type: PathPrefix
        value: /
